name: Build

# TODO Also publish velocity plugin on modrinth

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

env:
  # For any reason, specifying this in the modrinth step does not work?
  # But it is also well documented here, so this should be ok to do
  MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check tag condition
        if: startsWith(github.ref, 'refs/tags/')
        run: echo "Ref is a tag"

      - name: Check out project
        if: success()
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        if: success()
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'microsoft'

      - name: Setup Gradle
        if: success()
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.4

      - name: Build fabric-mod
        if: success()
        run: gradle :fabric-mod:remapJar

      - name: Build velocity-plugin
        if: success()
        run: gradle :velocity-plugin:shadowJar

      - name: Release on GitHub
        if: success() && startsWith(github.ref, 'refs/tags/') # Failsafe check again
        uses: softprops/action-gh-release@v1
        with:
          files: |
            **/libs/proxy-command-*.jar
            README.md
            CHANGELOG.md
            LICENSE
          body_path: CHANGELOG.md
          draft: false
          prerelease: false
          fail_on_unmatched_files: true
          